#COLOUR (Solarized dark)

# default statusbar colors
set-option -g status-bg default #base02
set-option -g status-fg default #yellow
set-option -g status-attr default

# default window title colors
set-window-option -g window-status-fg brightwhite
set-window-option -g window-status-bg default
#set-window-option -g window-status-attr dim

# active window title colors
set-window-option -g window-status-current-fg brightred #orange
set-window-option -g window-status-current-bg default
#set-window-option -g window-status-current-attr bright

# pane border
set-option -g pane-border-fg black #base02
set-option -g pane-active-border-fg brightgreen #base01

# message text
set-option -g message-bg black #base02
set-option -g message-fg brightred #orange

# pane number display
set-option -g display-panes-active-colour red
set-option -g display-panes-colour white

# clock
set-window-option -g clock-mode-colour green #green
set -g status-right '#[fg=brightwhite,bold] %b-%d %H:%M:%S '
setw -g window-status-current-format ' #I:#W#[fg=brightyellow]#F '
setw -g window-status-format ' #I:#W#[fg=brightyellow]#F '


# bell
set-window-option -g window-status-bell-style fg=black,bg=red #base02, red

# Enable mouse mode (tmux 2.1 and above)
set -g mouse on

# split panes using | and -
bind / split-window -h
bind - split-window -v
unbind '"'
unbind %


